### ISSUE TITLE
Latest version fails to build on rust rustc 1.96.0

### ISSUE THREAD

**Issue by michal-ciesielski-ph** [manojkarthick/pqrs#61]
Compiling arrow-arith v51.0.0
   Compiling arrow-row v51.0.0
error[E0034]: multiple applicable items in scope
   --> /home/michal/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-arith-51.0.0/src/temporal.rs:90:36
    |
 90 |         DatePart::Quarter => |d| d.quarter() as i32,
    |                                    ^^^^^^^ multiple `quarter` found
    |
note: candidate #1 is defined in the trait `ChronoDateExt`
   --> /home/michal/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-arith-51.0.0/src/temporal.rs:401:5
    |
401 |     fn quarter(&self) -> u32;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `Datelike`
   --> /home/michal/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/chrono-0.4.45/src/traits.rs:47:5
    |
 47 |     fn quarter(&self) -> u32 {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the method for candidate #1
    |
 90 -         DatePart::Quarter => |d| d.quarter() as i32,
 90 +         DatePart::Quarter => |d| ChronoDateExt::quarter(&d) as i32,
    |
help: disambiguate the method for candidate #2
    |
 90 -         DatePart::Quarter => |d| d.quarter() as i32,
 90 +         DatePart::Quarter => |d| Datelike::quarter(&d) as i32,
    |

**Comment by michal-ciesielski-ph** [comment]
This is issue when I install it via cargo:
`cargo install pqrs`
It is all good if I clone sources and build it locally.

**Comment by michal-ciesielski-ph** [comment]
oh, it's duplicate of https://github.com/manojkarthick/pqrs/issues/57 which can be fixed by dependencies update (https://github.com/manojkarthick/pqrs/pull/58)
